# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-demo-account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import mt5_term_api_gui_pb2 as mt5__term__api__gui__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmt5-term-api-demo-account.proto\x12\x0cmt5_term_api\x1a\x1cgoogle/api/annotations.proto\x1a\x16mt5-term-api-gui.proto2\x8b\x02\n\x0b\x44\x65moAccount\x12|\n\x0fOpenDemoAccount\x12\'.mt5_term_api.GuiDemoOpenAccountRequest\x1a%.mt5_term_api.GuiDemoOpenAccountReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/DemoAccount/Open\x12~\n\x1a\x44\x65moOpenAccountInteractive\x12-.mt5_term_api.GuiDemoInteractiveClientMessage\x1a-.mt5_term_api.GuiDemoInteractiveServerMessage(\x01\x30\x01\x42\x42Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\xaa\x02\x0cmt5_term_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mt5_term_api_demo_account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\252\002\014mt5_term_api'
  _DEMOACCOUNT.methods_by_name['OpenDemoAccount']._options = None
  _DEMOACCOUNT.methods_by_name['OpenDemoAccount']._serialized_options = b'\202\323\344\223\002\023\022\021/DemoAccount/Open'
  _DEMOACCOUNT._serialized_start=104
  _DEMOACCOUNT._serialized_end=371
# @@protoc_insertion_point(module_scope)
