# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_connection_pb2 as mt5__term__api__connection__pb2


class ConnectionStub(object):
    """-------------------------------------!!!! MT5 CONNECTION SERVICE START !!!!!!!---------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectEx = channel.unary_unary(
                '/mt5_term_api.Connection/ConnectEx',
                request_serializer=mt5__term__api__connection__pb2.ConnectExRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectExReply.FromString,
                )
        self.Connect = channel.unary_unary(
                '/mt5_term_api.Connection/Connect',
                request_serializer=mt5__term__api__connection__pb2.ConnectRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectReply.FromString,
                )
        self.ConnectProxy = channel.unary_unary(
                '/mt5_term_api.Connection/ConnectProxy',
                request_serializer=mt5__term__api__connection__pb2.ConnectProxyRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectProxyReply.FromString,
                )
        self.CheckConnect = channel.unary_unary(
                '/mt5_term_api.Connection/CheckConnect',
                request_serializer=mt5__term__api__connection__pb2.CheckConnectRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.CheckConnectReply.FromString,
                )
        self.ConnectState = channel.unary_unary(
                '/mt5_term_api.Connection/ConnectState',
                request_serializer=mt5__term__api__connection__pb2.ConnectStateRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectStateReply.FromString,
                )
        self.OnConnectState = channel.unary_stream(
                '/mt5_term_api.Connection/OnConnectState',
                request_serializer=mt5__term__api__connection__pb2.OnConnectStateRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.OnConnectStateReply.FromString,
                )
        self.ConnectionStatus = channel.unary_unary(
                '/mt5_term_api.Connection/ConnectionStatus',
                request_serializer=mt5__term__api__connection__pb2.ConnectionStatusRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectionStatusReply.FromString,
                )
        self.Disconnect = channel.unary_unary(
                '/mt5_term_api.Connection/Disconnect',
                request_serializer=mt5__term__api__connection__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.DisconnectReply.FromString,
                )
        self.Reconnect = channel.unary_unary(
                '/mt5_term_api.Connection/Reconnect',
                request_serializer=mt5__term__api__connection__pb2.ReconnectRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ReconnectReply.FromString,
                )
        self.ConnectByToken = channel.unary_unary(
                '/mt5_term_api.Connection/ConnectByToken',
                request_serializer=mt5__term__api__connection__pb2.ConnectByTokenRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectExReply.FromString,
                )
        self.GetBrokerServersByBrokerName = channel.unary_unary(
                '/mt5_term_api.Connection/GetBrokerServersByBrokerName',
                request_serializer=mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameReply.FromString,
                )
        self.Screenshot = channel.unary_unary(
                '/mt5_term_api.Connection/Screenshot',
                request_serializer=mt5__term__api__connection__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ScreenshotReply.FromString,
                )
        self.GetId = channel.unary_unary(
                '/mt5_term_api.Connection/GetId',
                request_serializer=mt5__term__api__connection__pb2.GetIdRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.GetIdReply.FromString,
                )
        self.ConnectStream = channel.unary_stream(
                '/mt5_term_api.Connection/ConnectStream',
                request_serializer=mt5__term__api__connection__pb2.ConnectRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectStreamEvent.FromString,
                )
        self.ConnectExStream = channel.unary_stream(
                '/mt5_term_api.Connection/ConnectExStream',
                request_serializer=mt5__term__api__connection__pb2.ConnectExRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.ConnectStreamEvent.FromString,
                )


class ConnectionServicer(object):
    """-------------------------------------!!!! MT5 CONNECTION SERVICE START !!!!!!!---------------------------------------

    """

    def ConnectEx(self, request, context):
        """Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
        [DefaultValues]
        {
        "user": "213889529",
        "password": "7dPjA*Jm",
        "mtClusterName": "OctaFX-Demo",
        "timeoutSeconds": "120"
        }  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Creates terminal connection to the MT5 server and returns Guid of it 
        [DefaultValues]
        {
        "user": "213889529",
        "password": "7dPjA*Jm",
        "host": "d51a1.octanetwork.net",
        "port": "443",
        "timeoutSeconds": "120"
        }  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectProxy(self, request, context):
        """Connect to account with user, password, host, port.
        [DefaultValues] 
        { 
        "user": "213889529", 
        "password": "7dPjA*Jm", 
        "host": "d51a1.octanetwork.net", 
        "port": "443", 
        "proxyUser": "ProxyUser123", 
        "proxyPassword": "qwerty123", 
        "proxyHost": "65.108.126.217", 
        "proxyPort": "1080", 
        "proxyType": "Socks5" 
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckConnect(self, request, context):
        """Checks if terminal connection to MT5 server is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectState(self, request, context):
        """Returns detailed live connection state of this terminal instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnConnectState(self, request, context):
        """Streams real-time connection state changes for specified or visible terminals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectionStatus(self, request, context):
        """Deprecated alias for ConnectState
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Close terminal connection to MT5 server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconnect(self, request, context):
        """If you need to recreate terminal instance with the same id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectByToken(self, request, context):
        """Rebuild a terminal instance from a previously-saved token_details_mt5 row. The id header
        names the terminal to bring back; every credential (User/Password/Server or Host+Port,
        proxy settings, servers.dat bytes, PfxFile, HardwareId, Build) is read from the DB. Same
        reply as ConnectEx so callers do not need a separate result path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrokerServersByBrokerName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """Captures the Xvfb display screenshot for the terminal instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetId(self, request, context):
        """Generates a deterministic GUID from user and password.
        The same user/password combination always produces the same GUID.
        Use this GUID as the 'id' header for Connect and other endpoints.
        [DefaultValues]
        {
        "user": "213889529",
        "password": "7dPjA*Jm"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectStream(self, request, context):
        """Same as Connect but streams real-time progress events.
        Requires 'id' header — use GetId to generate.
        Swagger does not support streaming — use /connect-stream interactive viewer.
        [DefaultValues]
        {
        "user": "213889529",
        "password": "7dPjA*Jm",
        "host": "d51a1.octanetwork.net",
        "port": "443",
        "timeoutSeconds": "120"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectExStream(self, request, context):
        """Same as ConnectEx but streams real-time progress events.
        Requires 'id' header — use GetId to generate.
        Swagger does not support streaming — use /connect-stream interactive viewer.
        [DefaultValues]
        {
        "user": "213889529",
        "password": "7dPjA*Jm",
        "mtClusterName": "OctaFX-Demo",
        "timeoutSeconds": "120"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectEx': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectEx,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectExRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectExReply.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectReply.SerializeToString,
            ),
            'ConnectProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectProxy,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectProxyRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectProxyReply.SerializeToString,
            ),
            'CheckConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConnect,
                    request_deserializer=mt5__term__api__connection__pb2.CheckConnectRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.CheckConnectReply.SerializeToString,
            ),
            'ConnectState': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectState,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectStateRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectStateReply.SerializeToString,
            ),
            'OnConnectState': grpc.unary_stream_rpc_method_handler(
                    servicer.OnConnectState,
                    request_deserializer=mt5__term__api__connection__pb2.OnConnectStateRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.OnConnectStateReply.SerializeToString,
            ),
            'ConnectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectionStatus,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectionStatusRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectionStatusReply.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=mt5__term__api__connection__pb2.DisconnectRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.DisconnectReply.SerializeToString,
            ),
            'Reconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconnect,
                    request_deserializer=mt5__term__api__connection__pb2.ReconnectRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ReconnectReply.SerializeToString,
            ),
            'ConnectByToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectByToken,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectByTokenRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectExReply.SerializeToString,
            ),
            'GetBrokerServersByBrokerName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrokerServersByBrokerName,
                    request_deserializer=mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameReply.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=mt5__term__api__connection__pb2.ScreenshotRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ScreenshotReply.SerializeToString,
            ),
            'GetId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetId,
                    request_deserializer=mt5__term__api__connection__pb2.GetIdRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.GetIdReply.SerializeToString,
            ),
            'ConnectStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ConnectStream,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectStreamEvent.SerializeToString,
            ),
            'ConnectExStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ConnectExStream,
                    request_deserializer=mt5__term__api__connection__pb2.ConnectExRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.ConnectStreamEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.Connection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connection(object):
    """-------------------------------------!!!! MT5 CONNECTION SERVICE START !!!!!!!---------------------------------------

    """

    @staticmethod
    def ConnectEx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/ConnectEx',
            mt5__term__api__connection__pb2.ConnectExRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectExReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/Connect',
            mt5__term__api__connection__pb2.ConnectRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/ConnectProxy',
            mt5__term__api__connection__pb2.ConnectProxyRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectProxyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/CheckConnect',
            mt5__term__api__connection__pb2.CheckConnectRequest.SerializeToString,
            mt5__term__api__connection__pb2.CheckConnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/ConnectState',
            mt5__term__api__connection__pb2.ConnectStateRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectStateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnConnectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Connection/OnConnectState',
            mt5__term__api__connection__pb2.OnConnectStateRequest.SerializeToString,
            mt5__term__api__connection__pb2.OnConnectStateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/ConnectionStatus',
            mt5__term__api__connection__pb2.ConnectionStatusRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectionStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/Disconnect',
            mt5__term__api__connection__pb2.DisconnectRequest.SerializeToString,
            mt5__term__api__connection__pb2.DisconnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/Reconnect',
            mt5__term__api__connection__pb2.ReconnectRequest.SerializeToString,
            mt5__term__api__connection__pb2.ReconnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectByToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/ConnectByToken',
            mt5__term__api__connection__pb2.ConnectByTokenRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectExReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBrokerServersByBrokerName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/GetBrokerServersByBrokerName',
            mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameRequest.SerializeToString,
            mt5__term__api__connection__pb2.GetBrokerServersByBrokerNameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/Screenshot',
            mt5__term__api__connection__pb2.ScreenshotRequest.SerializeToString,
            mt5__term__api__connection__pb2.ScreenshotReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Connection/GetId',
            mt5__term__api__connection__pb2.GetIdRequest.SerializeToString,
            mt5__term__api__connection__pb2.GetIdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Connection/ConnectStream',
            mt5__term__api__connection__pb2.ConnectRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectStreamEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectExStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Connection/ConnectExStream',
            mt5__term__api__connection__pb2.ConnectExRequest.SerializeToString,
            mt5__term__api__connection__pb2.ConnectStreamEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class LogsStub(object):
    """Provides access to terminal log content (Journal and Experts tabs).
    Reads log entries directly from the MT5 terminal GUI.
    Requires 'id' header with the terminal connection GUID returned by Connect.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Journal = channel.unary_unary(
                '/mt5_term_api.Logs/Journal',
                request_serializer=mt5__term__api__connection__pb2.JournalRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.JournalReply.FromString,
                )
        self.OnJournal = channel.unary_stream(
                '/mt5_term_api.Logs/OnJournal',
                request_serializer=mt5__term__api__connection__pb2.OnJournalRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.OnJournalReply.FromString,
                )
        self.Experts = channel.unary_unary(
                '/mt5_term_api.Logs/Experts',
                request_serializer=mt5__term__api__connection__pb2.JournalRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.JournalReply.FromString,
                )
        self.OnExperts = channel.unary_stream(
                '/mt5_term_api.Logs/OnExperts',
                request_serializer=mt5__term__api__connection__pb2.OnJournalRequest.SerializeToString,
                response_deserializer=mt5__term__api__connection__pb2.OnJournalReply.FromString,
                )


class LogsServicer(object):
    """Provides access to terminal log content (Journal and Experts tabs).
    Reads log entries directly from the MT5 terminal GUI.
    Requires 'id' header with the terminal connection GUID returned by Connect.
    """

    def Journal(self, request, context):
        """Returns log entries from the terminal Journal tab.
        The Journal tab contains system messages about terminal connection status, 
        network activity, server synchronization and other internal events.
        Works regardless of which tab is currently active in the terminal UI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnJournal(self, request, context):
        """Streams log entries from the terminal Journal tab in real-time.
        Requires 'id' header with the terminal connection GUID returned by Connect.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Experts(self, request, context):
        """Returns log entries from the terminal Experts tab.
        The Experts tab contains messages from Expert Advisors (EAs), scripts and indicators
        including Print() output, initialization/deinitialization events and runtime errors.
        Works regardless of which tab is currently active in the terminal UI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnExperts(self, request, context):
        """Streams log entries from the terminal Experts tab in real-time.
        Requires 'id' header with the terminal connection GUID returned by Connect.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Journal': grpc.unary_unary_rpc_method_handler(
                    servicer.Journal,
                    request_deserializer=mt5__term__api__connection__pb2.JournalRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.JournalReply.SerializeToString,
            ),
            'OnJournal': grpc.unary_stream_rpc_method_handler(
                    servicer.OnJournal,
                    request_deserializer=mt5__term__api__connection__pb2.OnJournalRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.OnJournalReply.SerializeToString,
            ),
            'Experts': grpc.unary_unary_rpc_method_handler(
                    servicer.Experts,
                    request_deserializer=mt5__term__api__connection__pb2.JournalRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.JournalReply.SerializeToString,
            ),
            'OnExperts': grpc.unary_stream_rpc_method_handler(
                    servicer.OnExperts,
                    request_deserializer=mt5__term__api__connection__pb2.OnJournalRequest.FromString,
                    response_serializer=mt5__term__api__connection__pb2.OnJournalReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.Logs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logs(object):
    """Provides access to terminal log content (Journal and Experts tabs).
    Reads log entries directly from the MT5 terminal GUI.
    Requires 'id' header with the terminal connection GUID returned by Connect.
    """

    @staticmethod
    def Journal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Logs/Journal',
            mt5__term__api__connection__pb2.JournalRequest.SerializeToString,
            mt5__term__api__connection__pb2.JournalReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnJournal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Logs/OnJournal',
            mt5__term__api__connection__pb2.OnJournalRequest.SerializeToString,
            mt5__term__api__connection__pb2.OnJournalReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Experts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Logs/Experts',
            mt5__term__api__connection__pb2.JournalRequest.SerializeToString,
            mt5__term__api__connection__pb2.JournalReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnExperts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Logs/OnExperts',
            mt5__term__api__connection__pb2.OnJournalRequest.SerializeToString,
            mt5__term__api__connection__pb2.OnJournalReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
