# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_admin_pb2 as mt5__term__api__admin__pb2


class AdminApiStub(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActiveTerminals = channel.unary_unary(
                '/mrpc_admin.AdminApi/ActiveTerminals',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsReply.FromString,
                )
        self.ActiveTerminalsCluster = channel.unary_unary(
                '/mrpc_admin.AdminApi/ActiveTerminalsCluster',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.FromString,
                )
        self.SystemUsage = channel.unary_unary(
                '/mrpc_admin.AdminApi/SystemUsage',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.SystemUsageReply.FromString,
                )
        self.ListLogFiles = channel.unary_unary(
                '/mrpc_admin.AdminApi/ListLogFiles',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.ListLogFilesReply.FromString,
                )
        self.GetLogFile = channel.unary_unary(
                '/mrpc_admin.AdminApi/GetLogFile',
                request_serializer=mt5__term__api__admin__pb2.GetLogFileRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.GetLogFileReply.FromString,
                )
        self.GetEventLogEntries = channel.unary_unary(
                '/mrpc_admin.AdminApi/GetEventLogEntries',
                request_serializer=mt5__term__api__admin__pb2.GetEventLogEntriesRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.GetEventLogEntriesReply.FromString,
                )
        self.CaptureSessionScreenshot = channel.unary_unary(
                '/mrpc_admin.AdminApi/CaptureSessionScreenshot',
                request_serializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.FromString,
                )
        self.CaptureSessionScreenshotOnPod = channel.unary_unary(
                '/mrpc_admin.AdminApi/CaptureSessionScreenshotOnPod',
                request_serializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotOnPodRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.FromString,
                )
        self.RefreshMrpcRest = channel.unary_unary(
                '/mrpc_admin.AdminApi/RefreshMrpcRest',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.RefreshMrpcRestReply.FromString,
                )


class AdminApiServicer(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    def ActiveTerminals(self, request, context):
        """Active terminals running on THIS pod.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveTerminalsCluster(self, request, context):
        """Active terminals across ALL pods of this StatefulSet/Deployment.
        Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemUsage(self, request, context):
        """Whole-machine CPU % and physical RAM (current + short history) for THIS pod.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogFiles(self, request, context):
        """Lists the diagnostic log files on \\host.lan\Data\logs (mrpc.log, startup.log,
        install.log, boot-diag.log, and any future additions) - the exact files the container's
        postStart hook tails into "kubectl logs", readable here without cluster/kubectl access.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogFile(self, request, context):
        """Content of one log file from \\host.lan\Data\logs (see ListLogFiles). Truncated to the
        LAST max_bytes bytes if larger (0 = server default, 256 KiB).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventLogEntries(self, request, context):
        """On-demand dump of recent Windows Event Log entries (Service Control Manager events,
        shutdown/restart events, Application errors) - the same data boot-diag.bat captures on a
        service state change, available here without waiting for that trigger.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureSessionScreenshot(self, request, context):
        """Screenshot of a Windows interactive session's whole desktop - a specific
        MrpcTerminalUser<N> session, or (if session_user_name is empty) the pod's main/autologon
        session, the one startup.bat runs in.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureSessionScreenshotOnPod(self, request, context):
        """Same as CaptureSessionScreenshot, but fanned out from THIS pod to a DIFFERENT pod by IP
        (mirroring the ActiveTerminalsCluster fan-out) - a browser can only reach the pod that is
        currently serving it, not other pods' ClusterIPs, so the cluster admin view asks whichever
        pod it's connected to relay the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshMrpcRest(self, request, context):
        """Runs, in-process (LocalSystem, no guest logon/SSH needed), the same refresh
        startup.bat performs on a successful ONLOGON boot: robocopy published-app (including
        mrpc-rest) from the host share, then create/start MrpcRestService. Exists because
        ONLOGON is unreliable (autologon-dependent) - this lets a stuck deploy be repaired
        through the Terminal Manager's own already-running gRPC/HTTP API instead of waiting
        on that trigger or requiring interactive guest access.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActiveTerminals': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveTerminals,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.ActiveTerminalsReply.SerializeToString,
            ),
            'ActiveTerminalsCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveTerminalsCluster,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.SerializeToString,
            ),
            'SystemUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemUsage,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.SystemUsageReply.SerializeToString,
            ),
            'ListLogFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogFiles,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.ListLogFilesReply.SerializeToString,
            ),
            'GetLogFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogFile,
                    request_deserializer=mt5__term__api__admin__pb2.GetLogFileRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.GetLogFileReply.SerializeToString,
            ),
            'GetEventLogEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventLogEntries,
                    request_deserializer=mt5__term__api__admin__pb2.GetEventLogEntriesRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.GetEventLogEntriesReply.SerializeToString,
            ),
            'CaptureSessionScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureSessionScreenshot,
                    request_deserializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.SerializeToString,
            ),
            'CaptureSessionScreenshotOnPod': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureSessionScreenshotOnPod,
                    request_deserializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotOnPodRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.SerializeToString,
            ),
            'RefreshMrpcRest': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshMrpcRest,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.RefreshMrpcRestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mrpc_admin.AdminApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminApi(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    @staticmethod
    def ActiveTerminals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/ActiveTerminals',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.ActiveTerminalsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActiveTerminalsCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/ActiveTerminalsCluster',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/SystemUsage',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.SystemUsageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLogFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/ListLogFiles',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.ListLogFilesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/GetLogFile',
            mt5__term__api__admin__pb2.GetLogFileRequest.SerializeToString,
            mt5__term__api__admin__pb2.GetLogFileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEventLogEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/GetEventLogEntries',
            mt5__term__api__admin__pb2.GetEventLogEntriesRequest.SerializeToString,
            mt5__term__api__admin__pb2.GetEventLogEntriesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CaptureSessionScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/CaptureSessionScreenshot',
            mt5__term__api__admin__pb2.CaptureSessionScreenshotRequest.SerializeToString,
            mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CaptureSessionScreenshotOnPod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/CaptureSessionScreenshotOnPod',
            mt5__term__api__admin__pb2.CaptureSessionScreenshotOnPodRequest.SerializeToString,
            mt5__term__api__admin__pb2.CaptureSessionScreenshotReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshMrpcRest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/RefreshMrpcRest',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.RefreshMrpcRestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
