# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_gui_pb2 as mt5__term__api__gui__pb2


class GuiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/mt5_term_api.Gui/Login',
                request_serializer=mt5__term__api__gui__pb2.GuiLoginRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiLoginReply.FromString,
                )
        self.BrokerSearch = channel.unary_unary(
                '/mt5_term_api.Gui/BrokerSearch',
                request_serializer=mt5__term__api__gui__pb2.GuiBrokerSearchRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiBrokerSearchReply.FromString,
                )
        self.LoginEx = channel.unary_unary(
                '/mt5_term_api.Gui/LoginEx',
                request_serializer=mt5__term__api__gui__pb2.GuiLoginExRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiLoginExReply.FromString,
                )
        self.CloseDialogs = channel.unary_unary(
                '/mt5_term_api.Gui/CloseDialogs',
                request_serializer=mt5__term__api__gui__pb2.GuiCloseDialogsRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiCloseDialogsReply.FromString,
                )
        self.DemoFindCompanies = channel.unary_unary(
                '/mt5_term_api.Gui/DemoFindCompanies',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
                )
        self.DemoServersAndTypes = channel.unary_unary(
                '/mt5_term_api.Gui/DemoServersAndTypes',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
                )
        self.DemoOpenAccount = channel.unary_unary(
                '/mt5_term_api.Gui/DemoOpenAccount',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
                )
        self.DemoEnumControls = channel.unary_unary(
                '/mt5_term_api.Gui/DemoEnumControls',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoEnumControlsRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoEnumControlsReply.FromString,
                )
        self.DemoOpenAccountWithProgress = channel.unary_stream(
                '/mt5_term_api.Gui/DemoOpenAccountWithProgress',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoProgressEvent.FromString,
                )


class GuiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrokerSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginEx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseDialogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoFindCompanies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoServersAndTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoOpenAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoEnumControls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoOpenAccountWithProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=mt5__term__api__gui__pb2.GuiLoginRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiLoginReply.SerializeToString,
            ),
            'BrokerSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.BrokerSearch,
                    request_deserializer=mt5__term__api__gui__pb2.GuiBrokerSearchRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiBrokerSearchReply.SerializeToString,
            ),
            'LoginEx': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginEx,
                    request_deserializer=mt5__term__api__gui__pb2.GuiLoginExRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiLoginExReply.SerializeToString,
            ),
            'CloseDialogs': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseDialogs,
                    request_deserializer=mt5__term__api__gui__pb2.GuiCloseDialogsRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiCloseDialogsReply.SerializeToString,
            ),
            'DemoFindCompanies': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoFindCompanies,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoFindCompaniesRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoFindCompaniesReply.SerializeToString,
            ),
            'DemoServersAndTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoServersAndTypes,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoServersAndTypesRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoServersAndTypesReply.SerializeToString,
            ),
            'DemoOpenAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoOpenAccount,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.SerializeToString,
            ),
            'DemoEnumControls': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoEnumControls,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoEnumControlsRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoEnumControlsReply.SerializeToString,
            ),
            'DemoOpenAccountWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.DemoOpenAccountWithProgress,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoProgressEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.Gui', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gui(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/Login',
            mt5__term__api__gui__pb2.GuiLoginRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiLoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BrokerSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/BrokerSearch',
            mt5__term__api__gui__pb2.GuiBrokerSearchRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiBrokerSearchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginEx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/LoginEx',
            mt5__term__api__gui__pb2.GuiLoginExRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiLoginExReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseDialogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/CloseDialogs',
            mt5__term__api__gui__pb2.GuiCloseDialogsRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiCloseDialogsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoFindCompanies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/DemoFindCompanies',
            mt5__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoServersAndTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/DemoServersAndTypes',
            mt5__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoOpenAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/DemoOpenAccount',
            mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoEnumControls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.Gui/DemoEnumControls',
            mt5__term__api__gui__pb2.GuiDemoEnumControlsRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoEnumControlsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoOpenAccountWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt5_term_api.Gui/DemoOpenAccountWithProgress',
            mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoProgressEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
