# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-vnc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16mt5-term-api-vnc.proto\x12\x0cmt5_term_api\"\x1a\n\x07VncData\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32K\n\nVncService\x12=\n\tVncStream\x12\x15.mt5_term_api.VncData\x1a\x15.mt5_term_api.VncData(\x01\x30\x01\x42\x42Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\xaa\x02\x0cmt5_term_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mt5_term_api_vnc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\252\002\014mt5_term_api'
  _VNCDATA._serialized_start=40
  _VNCDATA._serialized_end=66
  _VNCSERVICE._serialized_start=68
  _VNCSERVICE._serialized_end=143
# @@protoc_insertion_point(module_scope)
