# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_gui_pb2 as mt5__term__api__gui__pb2


class DemoAccountStub(object):
    """Demo account creation service.
    Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenDemoAccount = channel.unary_unary(
                '/mt5_term_api.DemoAccount/OpenDemoAccount',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
                )
        self.DemoOpenAccountInteractive = channel.stream_stream(
                '/mt5_term_api.DemoAccount/DemoOpenAccountInteractive',
                request_serializer=mt5__term__api__gui__pb2.GuiDemoInteractiveClientMessage.SerializeToString,
                response_deserializer=mt5__term__api__gui__pb2.GuiDemoInteractiveServerMessage.FromString,
                )


class DemoAccountServicer(object):
    """Demo account creation service.
    Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    def OpenDemoAccount(self, request, context):
        """Open a demo account. Full wizard flow: search → select → fill form → register.
        Returns login, password, and investor password for the new demo account.
        [DefaultValues]
        {
        "company": "MetaQuotes Ltd.",
        "firstName": "Test",
        "lastName": "User",
        "email": "test@test.com",
        "phone": "+1234567890",
        "timeoutSeconds": "60"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoOpenAccountInteractive(self, request_iterator, context):
        """Interactive step-by-step demo account opening wizard.
        Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenDemoAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDemoAccount,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.SerializeToString,
            ),
            'DemoOpenAccountInteractive': grpc.stream_stream_rpc_method_handler(
                    servicer.DemoOpenAccountInteractive,
                    request_deserializer=mt5__term__api__gui__pb2.GuiDemoInteractiveClientMessage.FromString,
                    response_serializer=mt5__term__api__gui__pb2.GuiDemoInteractiveServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.DemoAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoAccount(object):
    """Demo account creation service.
    Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    @staticmethod
    def OpenDemoAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.DemoAccount/OpenDemoAccount',
            mt5__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoOpenAccountInteractive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mt5_term_api.DemoAccount/DemoOpenAccountInteractive',
            mt5__term__api__gui__pb2.GuiDemoInteractiveClientMessage.SerializeToString,
            mt5__term__api__gui__pb2.GuiDemoInteractiveServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
