# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt5-term-api-demo-account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import mt5_term_api_gui_pb2 as mt5__term__api__gui__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmt5-term-api-demo-account.proto\x12\x0cmt5_term_api\x1a\x1cgoogle/api/annotations.proto\x1a\x16mt5-term-api-gui.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n\x16\x44\x65moAccountStreamEvent\x12\x0c\n\x04step\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x12\n\nelapsed_ms\x18\x04 \x01(\x03\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08is_final\x18\x06 \x01(\x08\x12;\n\x0c\x61\x63\x63ount_data\x18\x07 \x01(\x0b\x32%.mt5_term_api.GuiDemoOpenAccountReply2\xc1\x04\n\x0b\x44\x65moAccount\x12\x87\x01\n\rFindCompanies\x12).mt5_term_api.GuiDemoFindCompaniesRequest\x1a\'.mt5_term_api.GuiDemoFindCompaniesReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/DemoAccount/FindCompanies\x12\x9d\x01\n\x16ServersAndAccountTypes\x12+.mt5_term_api.GuiDemoServersAndTypesRequest\x1a).mt5_term_api.GuiDemoServersAndTypesReply\"+\x82\xd3\xe4\x93\x02%\x12#/DemoAccount/ServersAndAccountTypes\x12|\n\x0fOpenDemoAccount\x12\'.mt5_term_api.GuiDemoOpenAccountRequest\x1a%.mt5_term_api.GuiDemoOpenAccountReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/DemoAccount/Open\x12\x89\x01\n\x15OpenDemoAccountStream\x12\'.mt5_term_api.GuiDemoOpenAccountRequest\x1a$.mt5_term_api.DemoAccountStreamEvent\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/DemoAccount/OpenStream0\x01\x42\x42Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\xaa\x02\x0cmt5_term_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mt5_term_api_demo_account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1git.mtapi.io/root/mrpc-proto.git/mt5/libraries/go\252\002\014mt5_term_api'
  _DEMOACCOUNT.methods_by_name['FindCompanies']._options = None
  _DEMOACCOUNT.methods_by_name['FindCompanies']._serialized_options = b'\202\323\344\223\002\034\022\032/DemoAccount/FindCompanies'
  _DEMOACCOUNT.methods_by_name['ServersAndAccountTypes']._options = None
  _DEMOACCOUNT.methods_by_name['ServersAndAccountTypes']._serialized_options = b'\202\323\344\223\002%\022#/DemoAccount/ServersAndAccountTypes'
  _DEMOACCOUNT.methods_by_name['OpenDemoAccount']._options = None
  _DEMOACCOUNT.methods_by_name['OpenDemoAccount']._serialized_options = b'\202\323\344\223\002\023\022\021/DemoAccount/Open'
  _DEMOACCOUNT.methods_by_name['OpenDemoAccountStream']._options = None
  _DEMOACCOUNT.methods_by_name['OpenDemoAccountStream']._serialized_options = b'\202\323\344\223\002\031\022\027/DemoAccount/OpenStream'
  _DEMOACCOUNTSTREAMEVENT._serialized_start=137
  _DEMOACCOUNTSTREAMEVENT._serialized_end=353
  _DEMOACCOUNT._serialized_start=356
  _DEMOACCOUNT._serialized_end=933
# @@protoc_insertion_point(module_scope)
