# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_vnc_pb2 as mt5__term__api__vnc__pb2


class VncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VncStream = channel.stream_stream(
                '/mt5_term_api.VncService/VncStream',
                request_serializer=mt5__term__api__vnc__pb2.VncData.SerializeToString,
                response_deserializer=mt5__term__api__vnc__pb2.VncData.FromString,
                )


class VncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VncStream(self, request_iterator, context):
        """Bidirectional stream: raw VNC (RFB) binary data flows in both directions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VncStream': grpc.stream_stream_rpc_method_handler(
                    servicer.VncStream,
                    request_deserializer=mt5__term__api__vnc__pb2.VncData.FromString,
                    response_serializer=mt5__term__api__vnc__pb2.VncData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.VncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VncStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mt5_term_api.VncService/VncStream',
            mt5__term__api__vnc__pb2.VncData.SerializeToString,
            mt5__term__api__vnc__pb2.VncData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
