# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_admin_pb2 as mt5__term__api__admin__pb2


class AdminApiStub(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActiveTerminals = channel.unary_unary(
                '/mrpc_admin.AdminApi/ActiveTerminals',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsReply.FromString,
                )
        self.ActiveTerminalsCluster = channel.unary_unary(
                '/mrpc_admin.AdminApi/ActiveTerminalsCluster',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.FromString,
                )
        self.SystemUsage = channel.unary_unary(
                '/mrpc_admin.AdminApi/SystemUsage',
                request_serializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
                response_deserializer=mt5__term__api__admin__pb2.SystemUsageReply.FromString,
                )


class AdminApiServicer(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    def ActiveTerminals(self, request, context):
        """Active terminals running on THIS pod.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveTerminalsCluster(self, request, context):
        """Active terminals across ALL pods of this StatefulSet/Deployment.
        Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemUsage(self, request, context):
        """Whole-machine CPU % and physical RAM (current + short history) for THIS pod.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActiveTerminals': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveTerminals,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.ActiveTerminalsReply.SerializeToString,
            ),
            'ActiveTerminalsCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveTerminalsCluster,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.SerializeToString,
            ),
            'SystemUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemUsage,
                    request_deserializer=mt5__term__api__admin__pb2.ActiveTerminalsRequest.FromString,
                    response_serializer=mt5__term__api__admin__pb2.SystemUsageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mrpc_admin.AdminApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminApi(object):
    """============================================================
    Admin / diagnostics service.
    Auth via admin_key (matched against the ADMIN_KEY env setting).
    HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    ============================================================
    """

    @staticmethod
    def ActiveTerminals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/ActiveTerminals',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.ActiveTerminalsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActiveTerminalsCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/ActiveTerminalsCluster',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.ActiveTerminalsClusterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SystemUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mrpc_admin.AdminApi/SystemUsage',
            mt5__term__api__admin__pb2.ActiveTerminalsRequest.SerializeToString,
            mt5__term__api__admin__pb2.SystemUsageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
