# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_trading_helper_pb2 as mt5__term__api__trading__helper__pb2


class TradingHelperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderSend = channel.unary_unary(
                '/mt5_term_api.TradingHelper/OrderSend',
                request_serializer=mt5__term__api__trading__helper__pb2.OrderSendRequest.SerializeToString,
                response_deserializer=mt5__term__api__trading__helper__pb2.OrderSendReply.FromString,
                )
        self.OrderSendWithoutChecks = channel.unary_unary(
                '/mt5_term_api.TradingHelper/OrderSendWithoutChecks',
                request_serializer=mt5__term__api__trading__helper__pb2.OrderSendRequest.SerializeToString,
                response_deserializer=mt5__term__api__trading__helper__pb2.OrderSendReply.FromString,
                )
        self.OrderModify = channel.unary_unary(
                '/mt5_term_api.TradingHelper/OrderModify',
                request_serializer=mt5__term__api__trading__helper__pb2.OrderModifyRequest.SerializeToString,
                response_deserializer=mt5__term__api__trading__helper__pb2.OrderModifyReply.FromString,
                )
        self.OrderClose = channel.unary_unary(
                '/mt5_term_api.TradingHelper/OrderClose',
                request_serializer=mt5__term__api__trading__helper__pb2.OrderCloseRequest.SerializeToString,
                response_deserializer=mt5__term__api__trading__helper__pb2.OrderCloseReply.FromString,
                )


class TradingHelperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OrderSend(self, request, context):
        """Send market or pending order
        [DefaultValues]
        {
        "symbol": "EURUSD",
        "operation": "TMT5_ORDER_TYPE_BUY",
        "volume": "0.1"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderSendWithoutChecks(self, request, context):
        """Send market or pending order immediately, with no Market Watch or quotes preparation.
        Same request and reply as OrderSend, but nothing is checked first and quotes_wait_ms is
        ignored. Use only for a symbol already known to be streaming; otherwise the trade server
        rejects the order (ErrMarketLasttimeUnknown 4304 "no ticks" and friends).
        [DefaultValues]
        {
        "symbol": "EURUSD",
        "operation": "TMT5_ORDER_TYPE_BUY",
        "volume": "0.1"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderModify(self, request, context):
        """Modify market or pending order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderClose(self, request, context):
        """Close market or pending order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingHelperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderSend': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderSend,
                    request_deserializer=mt5__term__api__trading__helper__pb2.OrderSendRequest.FromString,
                    response_serializer=mt5__term__api__trading__helper__pb2.OrderSendReply.SerializeToString,
            ),
            'OrderSendWithoutChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderSendWithoutChecks,
                    request_deserializer=mt5__term__api__trading__helper__pb2.OrderSendRequest.FromString,
                    response_serializer=mt5__term__api__trading__helper__pb2.OrderSendReply.SerializeToString,
            ),
            'OrderModify': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderModify,
                    request_deserializer=mt5__term__api__trading__helper__pb2.OrderModifyRequest.FromString,
                    response_serializer=mt5__term__api__trading__helper__pb2.OrderModifyReply.SerializeToString,
            ),
            'OrderClose': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderClose,
                    request_deserializer=mt5__term__api__trading__helper__pb2.OrderCloseRequest.FromString,
                    response_serializer=mt5__term__api__trading__helper__pb2.OrderCloseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.TradingHelper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TradingHelper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OrderSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradingHelper/OrderSend',
            mt5__term__api__trading__helper__pb2.OrderSendRequest.SerializeToString,
            mt5__term__api__trading__helper__pb2.OrderSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderSendWithoutChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradingHelper/OrderSendWithoutChecks',
            mt5__term__api__trading__helper__pb2.OrderSendRequest.SerializeToString,
            mt5__term__api__trading__helper__pb2.OrderSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderModify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradingHelper/OrderModify',
            mt5__term__api__trading__helper__pb2.OrderModifyRequest.SerializeToString,
            mt5__term__api__trading__helper__pb2.OrderModifyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OrderClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradingHelper/OrderClose',
            mt5__term__api__trading__helper__pb2.OrderCloseRequest.SerializeToString,
            mt5__term__api__trading__helper__pb2.OrderCloseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
