# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt5_term_api_trade_stats_pb2 as mt5__term__api__trade__stats__pb2


class TradeStatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TradeStats = channel.unary_unary(
                '/mt5_term_api.TradeStats/TradeStats',
                request_serializer=mt5__term__api__trade__stats__pb2.TradeStatsRequest.SerializeToString,
                response_deserializer=mt5__term__api__trade__stats__pb2.TradeStatsReply.FromString,
                )
        self.TradeStatsEquityHistory = channel.unary_unary(
                '/mt5_term_api.TradeStats/TradeStatsEquityHistory',
                request_serializer=mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryRequest.SerializeToString,
                response_deserializer=mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryReply.FromString,
                )
        self.EquityHistory = channel.unary_unary(
                '/mt5_term_api.TradeStats/EquityHistory',
                request_serializer=mt5__term__api__trade__stats__pb2.EquityHistoryRequest.SerializeToString,
                response_deserializer=mt5__term__api__trade__stats__pb2.EquityHistoryReply.FromString,
                )
        self.TradeUnrealizedPL = channel.unary_unary(
                '/mt5_term_api.TradeStats/TradeUnrealizedPL',
                request_serializer=mt5__term__api__trade__stats__pb2.TradeUnrealizedPLRequest.SerializeToString,
                response_deserializer=mt5__term__api__trade__stats__pb2.TradeUnrealizedPLReply.FromString,
                )


class TradeStatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TradeStats(self, request, context):
        """Trading statistics calculated from order history and open orders
        [DefaultValues]
        {
        "from": "2024-01-01T00:00:00"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TradeStatsEquityHistory(self, request, context):
        """Trading statistics with equity history chart points
        [DefaultValues]
        {
        "from": "2024-01-01T00:00:00",
        "excludeSameBars": true
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EquityHistory(self, request, context):
        """Equity history curve points with drawdown calculation
        [DefaultValues]
        {
        "from": "2024-10-01T00:00:00",
        "excludeSameBars": true
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TradeUnrealizedPL(self, request, context):
        """Maximum and minimum unrealized profit/loss per trade
        [DefaultValues]
        {
        "from": "2024-01-01T00:00:00"
        }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeStatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TradeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.TradeStats,
                    request_deserializer=mt5__term__api__trade__stats__pb2.TradeStatsRequest.FromString,
                    response_serializer=mt5__term__api__trade__stats__pb2.TradeStatsReply.SerializeToString,
            ),
            'TradeStatsEquityHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.TradeStatsEquityHistory,
                    request_deserializer=mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryRequest.FromString,
                    response_serializer=mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryReply.SerializeToString,
            ),
            'EquityHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.EquityHistory,
                    request_deserializer=mt5__term__api__trade__stats__pb2.EquityHistoryRequest.FromString,
                    response_serializer=mt5__term__api__trade__stats__pb2.EquityHistoryReply.SerializeToString,
            ),
            'TradeUnrealizedPL': grpc.unary_unary_rpc_method_handler(
                    servicer.TradeUnrealizedPL,
                    request_deserializer=mt5__term__api__trade__stats__pb2.TradeUnrealizedPLRequest.FromString,
                    response_serializer=mt5__term__api__trade__stats__pb2.TradeUnrealizedPLReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5_term_api.TradeStats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TradeStats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TradeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradeStats/TradeStats',
            mt5__term__api__trade__stats__pb2.TradeStatsRequest.SerializeToString,
            mt5__term__api__trade__stats__pb2.TradeStatsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TradeStatsEquityHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradeStats/TradeStatsEquityHistory',
            mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryRequest.SerializeToString,
            mt5__term__api__trade__stats__pb2.TradeStatsEquityHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EquityHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradeStats/EquityHistory',
            mt5__term__api__trade__stats__pb2.EquityHistoryRequest.SerializeToString,
            mt5__term__api__trade__stats__pb2.EquityHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TradeUnrealizedPL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt5_term_api.TradeStats/TradeUnrealizedPL',
            mt5__term__api__trade__stats__pb2.TradeUnrealizedPLRequest.SerializeToString,
            mt5__term__api__trade__stats__pb2.TradeUnrealizedPLReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
